# Generated by Django 4.0.3 on 2022-07-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_desc_contact_content_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='desc',
        ),
    ]
